RESI-1 basic layouts
leon914/Residue pull request #1
Opened 2017-07-12 14:41 UTC by leon914

2017-07-12 14:58 UTC, DalwinderBagdi requested changes

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    @BindView(R.id.add_review)
What do you think this does?

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    private EditText editText1;
I am sure you can think of a better name than this!

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        FloatingActionButton addReviewButton = (FloatingActionButton) findViewById(R.id.add_review);
You should be able to use butterknife instead of doing findViewById

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +//                handler.urlBuilder(artistName);
Normally we add a TODO comment
Please can you align the //

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +            //will navigate to the album searching activity
Can you add TODO to the start of this comment please
//TODO: Navigate to the album searching activity

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        // Inflate the menu; this adds items to the action bar if it is present.
Do you need the comment?

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/res/layout/content_main.xml
> +        android:layout_width="0dp"
We always save these in the dimens file so we can easily reuse them again. That applies to all the hard coded dp

2017-07-12 14:58 UTC, DalwinderBagdi commented on app/src/main/res/layout/content_main.xml
> +        android:text="Search"
We store strings in the string.xml file

2017-07-12 14:59 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    @BindView(R.id.add_review)
Actually nothing currently, ive just realised ive actually binded it to the view below

2017-07-12 15:04 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    @BindView(R.id.add_review)
So do you know what you need to do to change it

2017-07-12 15:08 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        FloatingActionButton addReviewButton = (FloatingActionButton) findViewById(R.id.add_review);
i have tried it but its not binding and the app crashes instantly because of it

2017-07-12 15:28 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        // Inflate the menu; this adds items to the action bar if it is present.
Sorry it was there when I opened it, is it okay if I leave it there for context?

2017-07-12 15:29 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        // Inflate the menu; this adds items to the action bar if it is present.
yeh thats fine

2017-07-12 15:39 UTC, DalwinderBagdi requested changes
Some small changes

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    @BindView(R.id.searchButton) Button searchButton;
A lot better!

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
Could you use BindView for this

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +//                handler.urlBuilder(artistName);
I meant align them so they are next to the text but still align with each other.

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="80dp"
add to the dimens file

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/res/layout/content_main.xml
> +        android:layout_marginEnd="11dp"
add to dimens file

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/res/layout/content_main.xml
> +        android:layout_marginTop="0dp"
add to dimens file

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/res/layout/content_main.xml
> +        android:layout_marginRight="0dp" />
add to dimens file

2017-07-12 15:39 UTC, DalwinderBagdi commented on app/src/main/res/values/dimens.xml
> +    <dimen name="fab_margin">16dp</dimen>
fab_margin? Can you think of another name

2017-07-13 08:45 UTC, jtfernandes-sky requested changes

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/androidTest/java/com/example/lhi06/residue/ExampleInstrumentedTest.java
> +package com.example.lhi06.residue;
Can you delete this class? This is just a sample test which adds nothing to the project

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/main/AndroidManifest.xml
> +        android:supportsRtl="true"
are you sure you want to support RTL layouts?

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        searchButton.setOnClickListener(new View.OnClickListener() {
Will the app not crash here with a `NullPointerException`?

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        if (id == R.id.action_settings) {
Will you have any settings in the app?

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +         //noinspection SimplifiableIfStatement
This shouldn't be ignored with this comment. You can simplify this if statement

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/main/res/layout/activity_main.xml
> +<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
Why are you using a `CoordinatorLayout`

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/main/res/layout/content_main.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Why are you using a `ConstraintLayout`?

2017-07-13 08:45 UTC, jtfernandes-sky commented on app/src/test/java/com/example/lhi06/residue/ExampleUnitTest.java
> +package com.example.lhi06.residue;
Can you delete these sample test?

2017-07-13 08:55 UTC, leon914 commented on app/src/main/AndroidManifest.xml
> +        android:supportsRtl="true"
im not sure what it means but the internet basically said no

2017-07-13 08:56 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        searchButton.setOnClickListener(new View.OnClickListener() {
it hasnt been, should it?

2017-07-13 08:59 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        if (id == R.id.action_settings) {
Im not sure, it was here when i created the activity so i think im going to leave it incase i need it at any point

2017-07-13 09:19 UTC, leon914 commented on app/src/main/res/layout/activity_main.xml
> +<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
I dont really know what it does, it was there when i made it and ive read up about it but dont really understand it

2017-07-13 09:20 UTC, leon914 commented on app/src/main/res/layout/content_main.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
I dont really know what it does, i know its similar to a relative layout but again it was there when i got here

2017-07-13 09:27 UTC, jtfernandes-sky commented on app/src/main/AndroidManifest.xml
> +        android:supportsRtl="true"
Here is some info on RTL: https://medium.com/@zhangqichuan/rtl-support-in-android-898e11f31561

I would say you don't want to support it :)

2017-07-13 09:28 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        if (id == R.id.action_settings) {
I would remove it and add it if you need it. Having code hanging around just because you might need it later is not a good practice

2017-07-13 09:28 UTC, leon914 commented on app/src/main/AndroidManifest.xml
> +        android:supportsRtl="true"
i read the first line about languages being read right to left and instantly deleted it

2017-07-13 09:29 UTC, jtfernandes-sky commented on app/src/main/res/layout/activity_main.xml
> +<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
`CoordinatorLayout` is quite advanced, I wouldn't recommend using it here.

Do you have a sketch of what the app will look like?

2017-07-13 09:29 UTC, jtfernandes-sky commented on app/src/main/res/layout/content_main.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Again, I would go with a more common layout here

2017-07-13 09:34 UTC, leon914 commented on app/src/main/res/layout/activity_main.xml
> +<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
yeh but the way i want to do it im not sure how to go about it

2017-07-13 10:17 UTC, david-williams-sky requested changes

2017-07-13 10:17 UTC, david-williams-sky commented on app/build.gradle
> +    compile 'com.jakewharton:butterknife-compiler:8.7.0'
Remove any dependencies you aren't currently using and add them back in as required - general rule: don't have anything in the app you aren't using even if you think you might need it in the future. The reason for this is the development process might not pan out the way you plan, libs might get superseded/deprecated or requirements might change and you'll be left with bloated code/apk which will be harder for others to understand and you will have to spend time figuring out which bits are actually used and cleaning up the rest

2017-07-13 10:17 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
As a general rule method parameters should never be re-assigned and should always be made 'final'. If you ever find you need to re-assign a method parameter then it's probably because your code design is wrong.

You can configure Android Studio to automatically add the 'final' for you in generated code - look in Preferences->Editor->Code Style->Java->Code Completion->Final Modifier

2017-07-13 10:17 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        searchButton.setOnClickListener(new View.OnClickListener() {
Look at using RetroLambda and using lambdas for click listeners

2017-07-13 10:17 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +            public void onClick(View view) {
final

2017-07-13 10:17 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
final

2017-07-13 10:17 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    public boolean onOptionsItemSelected(MenuItem item) {
final

2017-07-13 10:17 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        int id = item.getItemId();
You probably won't want to re-assign a different value to 'id' so make it final

2017-07-13 10:56 UTC, leon914 commented on app/build.gradle
> +    compile 'com.jakewharton:butterknife-compiler:8.7.0'
These were just the dependencies that are on my worksheet that dalli wrote for me to read through, but i understand what you mean, should i still delete the ones im not currently using or?

2017-07-13 10:59 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
You got rid of the toolbar so you don't have options menu anymore so you can get rid of this method and `menu_main.xml`

2017-07-13 11:00 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
just done it haha, ill re push

2017-07-13 11:07 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        searchButton.setOnClickListener(new View.OnClickListener() {
i haven't done lambdas yet :/

2017-07-13 11:07 UTC, david-williams-sky commented on app/build.gradle
> +    compile 'com.jakewharton:butterknife-compiler:8.7.0'
Yes delete them

2017-07-13 11:09 UTC, david-williams-sky commented on app/src/main/java/com/example/lhi06/residue/MainActivity.java
> +        searchButton.setOnClickListener(new View.OnClickListener() {
Sorry I thought you had done them - don't bother then for now.

2017-07-13 11:57 UTC, merged