Resi 39 deleting reviews
leon914/Residue pull request #8
Opened 2017-07-27 14:00 UTC by leon914

2017-07-27 14:07 UTC, jtfernandes-sky requested changes

2017-07-27 14:07 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        holder.albumArt.setOnClickListener(new View.OnClickListener() {
have you tried keeping setting the click listener on `holder.rootView` and `holder.deleteButton` only?

2017-07-27 14:07 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        @BindView(R.id.review_preview_row) LinearLayout rootView;
Why did you change this from `View` to `LinearLayout`?

2017-07-27 14:07 UTC, jtfernandes-sky commented on app/src/main/res/layout/review_row.xml
> +        android:src="@mipmap/ic_launcher"/>
why do you want this as `src`?

2017-07-27 14:07 UTC, jtfernandes-sky commented on app/src/main/res/layout/review_row.xml
> +                android:layout_width="40dp"
Why not `wrap_content` for both width and height?

2017-07-27 14:11 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        holder.albumArt.setOnClickListener(new View.OnClickListener() {
No, i thought the rootView would just overwrite the deleteButton, ill try it now

2017-07-27 14:12 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        @BindView(R.id.review_preview_row) LinearLayout rootView;
because i was having an issue where it couldnt find the layout and i found it easier to read as a LinearLayout, is this a bad change or?

2017-07-27 14:13 UTC, leon914 commented on app/src/main/res/layout/review_row.xml
> +        android:src="@mipmap/ic_launcher"/>
for testing sorry otherwise the mock looked really weird

2017-07-27 14:14 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        @BindView(R.id.review_preview_row) LinearLayout rootView;
Should be as generic as possible. So if you don't need anything specific from the LinearLayout the field should be View

2017-07-27 14:14 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        holder.albumArt.setOnClickListener(new View.OnClickListener() {
so this works :P

2017-07-27 14:17 UTC, leon914 commented on app/src/main/res/layout/review_row.xml
> +                android:layout_width="40dp"
because it covers the name if it is (the width goes really wide for just an X :/), but i will put these numbers and text from this into strings etc.

2017-07-27 14:31 UTC, jtfernandes-sky commented on app/src/main/res/layout/review_row.xml
> +                android:layout_width="40dp"
covers what text? Numbers should not be in the strings file

2017-07-27 14:32 UTC, jtfernandes-sky commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        holder.albumArt.setOnClickListener(new View.OnClickListener() {
Do you understand why it works?

2017-07-27 14:33 UTC, leon914 commented on app/src/main/java/com/example/lhi06/residue/ReviewAdapter.java
> +        holder.albumArt.setOnClickListener(new View.OnClickListener() {
im guessing that the rootView sets anything that hasnt been set to something different to whatever rootView is

2017-07-27 14:35 UTC, leon914 commented on app/src/main/res/layout/review_row.xml
> +                android:layout_width="40dp"
i put the numbers in the dimens file and the X in the strings file, and it covered the top textview if the name was over 7+ characters if the width was on wrap content

2017-07-27 14:36 UTC, david-williams-sky approved these changes
LGTM 👍

2017-07-28 11:41 UTC, jtfernandes-sky approved these changes

2017-07-28 13:08 UTC, merged